version: "3"

services:
  janusgraph:
    image: docker.io/janusgraph/janusgraph:0.6.1
    container_name: jce-janusgraph
    env_file:
      - janusgraph.env
    ports:
      - "8182:8182"
    networks:
      - jce-network

  cassandra:
    image: cassandra:3
    container_name: jce-cassandra
    ports:
      - "9042:9042"
      - "9160:9160"
    networks:
      - jce-network
    volumes:
      - janusgraph-data:/var/lib/cassandra

  elasticsearch:
    image: opensearchproject/opensearch:1.2.4
    container_name: jce-elastic
    env_file:
      - opensearch.env
    ports:
      - "9200:9200"
    networks:
      - jce-network
    volumes:
      - janusgraph-index:/usr/share/elasticsearch/data

  grafana:
    image: grafana/grafana-oss:8.4.5
    ports:
      - "3000:3000"
    networks:
      - jce-network
    volumes:
      - grafana-storage:/var/lib/grafana

  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - "2003"
      - "80"
      - "8080"
    networks:
      - jce-network

  dashboard:
    image: opensearchproject/opensearch-dashboards:1.2.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    environment:
      OPENSEARCH_HOSTS: '["https://elasticsearch:9200"]'
    networks:
      - jce-network

networks:
  jce-network:

volumes:
  janusgraph-data:
  janusgraph-index:
  grafana-storage:
